basePath: /api/v1
definitions:
  hattrick.InitiateHattrickRequest:
    properties:
      school:
        items:
          type: string
        type: array
    type: object
  hattrick.InitiateHattrickResponse:
    properties:
      blocked:
        items:
          type: string
        type: array
      running:
        items:
          type: string
        type: array
    type: object
info:
  contact: {}
paths:
  /example/helloworld:
    get:
      consumes:
      - application/json
      description: do ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: ping example
      tags:
      - example
  /hattrick/run:
    post:
      consumes:
      - application/json
      description: run hattrick
      parameters:
      - description: List of Schools to Run
        in: body
        name: requestBody
        required: true
        schema:
          $ref: '#/definitions/hattrick.InitiateHattrickRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/hattrick.InitiateHattrickResponse'
      summary: Run Hattrick
      tags:
      - hattrick
swagger: "2.0"
